/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed-variant": "#005048",
        "surface-container-high": "#2a2a2b",
        "inverse-surface": "#e5e2e3",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary-container": "#eeefff",
        "surface-tint": "#b4c5ff",
        "surface-dim": "#131314",
        "secondary-container": "#571bc1",
        "outline-variant": "#434655",
        "surface": "#131314",
        "surface-variant": "#353436",
        "on-background": "#e5e2e3",
        "inverse-on-surface": "#313031",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0e0e0f",
        "on-tertiary-container": "#b1fff1",
        "error": "#ffb4ab",
        "inverse-primary": "#0053db",
        "tertiary-fixed": "#71f8e4",
        "outline": "#8d90a0",
        "primary-container": "#2563eb",
        "primary": "#b4c5ff",
        "on-tertiary-fixed": "#00201c",
        "on-surface-variant": "#c3c6d7",
        "tertiary-container": "#007b6e",
        "on-primary-fixed": "#00174b",
        "secondary-fixed-dim": "#d0bcff",
        "on-primary": "#002a78",
        "tertiary-fixed-dim": "#4fdbc8",
        "on-secondary-fixed-variant": "#5516be",
        "primary-fixed": "#dbe1ff",
        "on-tertiary": "#003731",
        "on-error": "#690005",
        "on-surface": "#e5e2e3",
        "on-secondary-fixed": "#23005c",
        "tertiary": "#4fdbc8",
        "surface-bright": "#3a393a",
        "surface-container-low": "#1c1b1c",
        "background": "#131314",
        "surface-container": "#201f20",
        "primary-fixed-dim": "#b4c5ff",
        "error-container": "#93000a",
        "on-secondary-container": "#c4abff",
        "secondary-fixed": "#e9ddff",
        "secondary": "#d0bcff",
        "on-secondary": "#3c0091",
        "surface-container-highest": "#353436"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "stack-md": "16px",
        "margin-page": "40px",
        "container-max-width": "1440px",
        "gutter": "24px",
        "stack-sm": "8px",
        "stack-lg": "32px"
      },
      "fontFamily": {
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "mono-label": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "mono-label": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
